// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_l7zGboQxux_Rvzt1wrctF8gmc0sOkk',
    appId: '1:1083423857997:web:8f56d04f84c32eacf7ab04',
    messagingSenderId: '1083423857997',
    projectId: 'newtodoapp-cacf9',
    authDomain: 'newtodoapp-cacf9.firebaseapp.com',
    storageBucket: 'newtodoapp-cacf9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0T0eQiWwwAMSL99iNChy4j6Ij7f2BiqE',
    appId: '1:1083423857997:android:5b75e3d96529e639f7ab04',
    messagingSenderId: '1083423857997',
    projectId: 'newtodoapp-cacf9',
    storageBucket: 'newtodoapp-cacf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDscs7XSk_dJQhqtmU8ZgBih4B6lgqWnig',
    appId: '1:1083423857997:ios:fd45d15299bbc42df7ab04',
    messagingSenderId: '1083423857997',
    projectId: 'newtodoapp-cacf9',
    storageBucket: 'newtodoapp-cacf9.firebasestorage.app',
    iosBundleId: 'com.example.newTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_l7zGboQxux_Rvzt1wrctF8gmc0sOkk',
    appId: '1:1083423857997:web:3923b5c06ae03b37f7ab04',
    messagingSenderId: '1083423857997',
    projectId: 'newtodoapp-cacf9',
    authDomain: 'newtodoapp-cacf9.firebaseapp.com',
    storageBucket: 'newtodoapp-cacf9.firebasestorage.app',
  );
}
